### ISSUE TITLE
No manifest.json file found 'manifest.json'

### ISSUE THREAD

**Issue by urbatecte** [nyroDev/home-assistant-meteo-france-next-rain-card#1]
Hi @nyroDev ,

Thanks for this promising card.

Unfortunatly, I've try to install through HACS and got this error message:
"No manifest.json file found 'manifest.json'"

If you can have a look, it will be great.
Thanks a lot et bonne journée à Besançon 😄

**Comment by nyroDev** [comment]
Hi @urbatecte,
I updated the doc to be way more verbose.
When you add the repository into HACS, be sure to choose "Lovelace" in the category field and it will work.

**Comment by urbatecte** [comment]
Perfect !
Many thanks

<img width="232" alt="image" src="https://user-images.githubusercontent.com/37276346/193464978-b27b1959-9c35-4fa7-99d2-c3c4eb0d499c.png">
